all:
  vars:
    ansible_user: owner # default user for SSH
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

  children:
    baremetals: # Baremetals on-prem
      vars:
          ansible_user: maruthisi
      hosts:

    workstations: # workstation computers for lab exams
      vars:
        ansible_user: maruthisi # default user for SSH
      hosts:
        nfvsrv1:
#         ansible_host: 192.0.2.2
#         ansible_host: 10.9.66.189
          ansible_host: 10.9.64.176
          vms:
            - maas-regctrl
          lxds:
            - natrtr
            - coresw
            - dnssrv
            - maas-rackctrl

 
    vms: # VMs running on either baremetals or in cloud
      hosts:
        maas-regctrl:
          ansible_host: 192.0.2.27

    lxds: # Containers running on baremetals or VMs
      hosts:
        natrtr:
          ansible_host: 198.19.255.50
        coresw:
          ansible_host: 198.19.255.1
        dnssrv:
          ansible_host: 192.0.2.6
        maas-rackctrl:
          ansible_host: 198.18.0.27


