container_name: dnssrv
image_alias: images:debian/12/cloud
lxd_profile: dns-server-profile
user_name: owner
ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

interfaces:
  - name: eth0
    parent: br-noc
    mode: static
    address: 192.0.2.6/24
    routes:
    - to: "0.0.0.0/0"
      via: "192.0.2.1"
    dns:
    - 192.168.35.52
    - 192.168.36.53

packages:
  - cloud-init
  - netplan.io
  - openssh-server

dns_zone: "newslab-5g-testbed.cse.iith.ac.in"
dns_zone_file: "newslab-5g-testbed.cse.iith.ac.in"
dns_forwarders:
  - 192.168.36.53
  - 192.168.35.52
