container_name: coresw
image_alias: images:debian/12/cloud
lxd_profile: core-switch-profile
user_name: owner
ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

interfaces:
  - name: eth0
    parent: br-isl
    mode: static
    address: 198.19.255.1/24
    routes:
      - to: 0.0.0.0/0
        via: 198.19.255.50
      - to: 198.19.254.0/24
        via: 198.19.255.49
    dns:
      - 192.168.35.52
      - 192.168.36.53
  - name: eth1
    parent: br-noc
    mode: static
    address: 192.0.2.1/24
  - name: eth2
    parent: br-lan
    mode: static
    address: 198.18.0.1/24

packages:
  - openssh-server
  - netplan.io
  - tcpdump

lan_interfaces:
  - iface: eth1
    ip: "192.0.2.1"
    cidr: 24
  - iface: eth2
    ip: "198.18.0.1"
    cidr: 24


